services:
  mysql:
    image: mysql:latest
    container_name: carloso_mysql
    networks:
      - carloso-network
    environment:
      TZ: America/Montevideo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carlosowebsitedb
    ports:
      - "33069:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  carloso-network:
    name: carloso-network-default
