spring:
  application:
    name: carloso-website

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
  
  datasource:
    url: jdbc:mysql://localhost:33069/carlosowebsitedb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  
  liquibase:
    change-log: classpath:db/changelog.yml
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Domain registration date
domain:
  registration:
    date: 2016-08-16T08:30:00